### ISSUE TITLE
求教报错EnvironmentError: HTTPSConnectionPool

### ISSUE THREAD

**Issue by shy1997** [East196/sorrypy#11]
下载中间出了问题，不清楚为什么，是我个人的网络代理问题吗？
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/2c/af/f04cd614c5125a1b2d47324ec0f16fdae3abe1df5bacc4f4d80db7b679c1/imageio_ffmpeg-0.3.0-py3-none-win_amd64.whl (Caused by ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000025EAD36D100>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)'))

**Comment by East196** [comment]
有可能，可以考虑关了代理
