### ISSUE TITLE
提交后按钮一直停在"请稍后"

### ISSUE THREAD

**Issue by cjydayang** [East196/sorrypy#3]
打出的日志停留在下面的一句话
`ffmpeg -i static/sorry/template.mp4 -r 8 -vf ass=static/cache/sorry-d1911fe36d7b58c9f7b3950bb62bd2fb.gif.ass,scale=300:-1 -y static/cache/sorry-d1911fe36d7b58c9f7b3950bb62bd2fb.gif`

cpu和内存占用都很正常,不像是服务器卡住的问题啊?

**Comment by xukeqin** [comment]
权限问题，你可以直接运行下ffmpeg -i static/sorry/template.mp4 -r 8 -vf ass=static/cache/sorry-d1911fe36d7b58c9f7b3950bb62bd2fb.gif.ass,scale=300:-1 -y static/cache/sorry-d1911fe36d7b58c9f7b3950bb62bd2fb.gif这个命令，就可以发现问题所在~

**Comment by East196** [comment]
我之前碰到这个问题是由于ffmpeg的依赖ass库没有装好。如果是windows，直接用ffmpeg应该不会有这个问题。linux下，ffmpeg安装的时候要用 yum -y install libass libass-devel 先装好libass。希望有所帮助。 @cjydayang

**Comment by cjydayang** [comment]
@East196 感谢,安装完后正常运行
