### ISSUE TITLE
点击保存就404

### ISSUE THREAD

**Issue by wo8335224** [East196/sorrypy#4]
404 Not Found

**Comment by wo8335224** [comment]
127.0.0.1 - - [22/Mar/2018 10:34:25] "GET /static/cache/wangjingze-2a0ddd69d1ba7fe08e9ed36c7b804261.gif HTTP/1.1" 404 -

**Comment by EatMedicine** [comment]
未安装好ffmpeg 建议手动安装下 我之前也是这样的

**Comment by East196** [comment]
是的，一般是由于ffmpeg安装失败或错误，可以先用ffmpeg命令检查下安装。 @wo8335224
