### ISSUE TITLE
使用时报TypeError: the JSON object must be str, not 'bytes'的错误

### ISSUE THREAD

**Issue by rampageyjq** [East196/sorrypy#9]
使用时报TypeError: the JSON object must be str, not 'bytes'的错误，我把app.py里面a = request.get_data()改成了  a = request.get_data().decode('utf-8')就没有报错了，不知道是我环境的问题还是都有这个请况

**Comment by uroot666** [comment]
我也是报了这个错误，编码问题。

**Comment by East196** [comment]
这个情况可能是Python的版本问题
